"""Verification tests for Burst_Probability_Calc().

# ============================================================
# MATLAB GROUND TRUTH (lines 1083-1132)
# Computes probability of error bursts of lengths 1..min(ndfe,nburst).
# p_burst = cumprod(p_error_propagation).
# p_error_propagation[k] = P(noise > error_threshold) under burst k.
# ============================================================
"""
import numpy as np
import pytest
from types import SimpleNamespace
import sys, os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", ".."))
from com_functions.fn.Burst_Probability_Calc.py_impl import Burst_Probability_Calc


def _gaussian_pdf(BinSize=0.01, sigma=0.05, N=200):
    x = np.arange(-N, N + 1) * BinSize
    y = np.exp(-0.5 * (x / sigma) ** 2)
    y /= y.sum()
    return SimpleNamespace(BinSize=BinSize, Min=-N, x=x, y=y)


def _snr_struct():
    return SimpleNamespace(
        A_s=1.0,
        combined_interference_and_noise_pdf=_gaussian_pdf(),
    )


def _param(ndfe=3):
    return SimpleNamespace(
        pass_threshold=3.0,
        ndfe=ndfe,
        levels=4,
        delta_y=0.01,
    )


def _op(nburst=3, simple=True):
    return SimpleNamespace(
        COM_EP_margin=0.0,
        nburst=nburst,
        use_simple_EP_model=simple,
    )


def test_returns_two_outputs():
    """Returns (p_burst, p_error_propagation)."""
    result = Burst_Probability_Calc(_snr_struct(), [0.3, 0.2, 0.1], _param(), _op())
    assert len(result) == 2


def test_p_burst_length():
    """p_burst has length min(ndfe, nburst)."""
    p_burst, p_ep = Burst_Probability_Calc(_snr_struct(), [0.3, 0.2, 0.1], _param(3), _op(3))
    assert len(p_burst) == len(p_ep)
    assert len(p_burst) == min(3, 3)


def test_p_burst_is_cumprod():
    """p_burst = cumprod(p_error_propagation)."""
    p_burst, p_ep = Burst_Probability_Calc(_snr_struct(), [0.3, 0.2, 0.1], _param(), _op())
    np.testing.assert_allclose(p_burst, np.cumprod(p_ep))


def test_p_values_in_zero_one():
    """All probabilities are in [0, 1]."""
    p_burst, _ = Burst_Probability_Calc(_snr_struct(), [0.3, 0.2, 0.1], _param(), _op())
    assert np.all(p_burst >= 0) and np.all(p_burst <= 1)


def test_no_dfe_taps_returns_length_one():
    """With ndfe=1 and nburst=1, result has length 1."""
    p_burst, p_ep = Burst_Probability_Calc(_snr_struct(), [], _param(ndfe=1), _op(nburst=1))
    assert len(p_burst) == 1
    assert len(p_ep) == 1


# ============================================================
# COM Octave 4p16p0 oracle pins.
# Generated by running Burst_Probability_Calc verbatim from
# octave/com_ieee8023_4p16p0_octave_compat.m under Octave, with
# get_pdf_from_sampled_signal taken from matlab/com_ieee8023_4p16p0.m
# (the compat copy is a rewritten speed variant).
# Inputs: the Gaussian pdf above (BinSize 0.01, sigma 0.05, N 200),
# A_s=1, pass_threshold=3, COM_EP_margin=0, levels=4, delta_y=0.01.
# ============================================================

_OCT_SIMPLE_BURST = [1.386500771629333e-45, 6.138986258987091e-48,
                     2.7181486703209421e-50]
_OCT_SIMPLE_EP = [1.386500771629333e-45, 0.0044276832617791625,
                  0.0044276832617791625]
_OCT_FULL_BURST = [1.386500771629333e-45, 6.138986258987091e-48,
                   6.5590033373435021e-49]
_OCT_FULL_EP = [1.386500771629333e-45, 0.0044276832617791625,
                0.10684179863966192]
# DFE_taps=[] with ndfe=nburst=3, simple model: MATLAB max([]) is [], the
# post-error pdf is the delta at zero, so every burst repeats the first.
_OCT_EMPTY_EP = [1.386500771629333e-45] * 3
_OCT_EMPTY_BURST = [1.386500771629333e-45, 1.9223843897287357e-90,
                    2.6653874397270765e-135]


def test_octave_simple_ep_model_values():
    """COM Octave: simple EP model reuses the largest tap for every burst."""
    p_burst, p_ep = Burst_Probability_Calc(
        _snr_struct(), [0.3, 0.2, 0.1], _param(), _op(simple=True))
    np.testing.assert_allclose(p_ep, _OCT_SIMPLE_EP, rtol=1e-13)
    np.testing.assert_allclose(p_burst, _OCT_SIMPLE_BURST, rtol=1e-13)


def test_octave_full_ep_model_values():
    """COM Octave: the full model walks down the sorted taps, k-th burst
    convolving onto the (k-1)-th pdf rather than onto the first."""
    p_burst, p_ep = Burst_Probability_Calc(
        _snr_struct(), [0.3, 0.2, 0.1], _param(), _op(simple=False))
    np.testing.assert_allclose(p_ep, _OCT_FULL_EP, rtol=1e-13)
    np.testing.assert_allclose(p_burst, _OCT_FULL_BURST, rtol=1e-13)


def test_octave_empty_taps_simple_model_is_not_an_error():
    """COM Octave: an empty DFE_taps under the simple model is legal.

    max([]) is [], 2*A_s*[] stays empty, and
    `if max(abs(input_vector)) > BinSize` is false on an empty comparison, so
    get_pdf_from_sampled_signal returns the delta at zero.  np.max raised.
    """
    p_burst, p_ep = Burst_Probability_Calc(
        _snr_struct(), [], _param(ndfe=3), _op(nburst=3, simple=True))
    np.testing.assert_allclose(p_ep, _OCT_EMPTY_EP, rtol=1e-13)
    np.testing.assert_allclose(p_burst, _OCT_EMPTY_BURST, rtol=1e-13)


def test_octave_empty_taps_full_model_raises():
    """COM Octave: the full model indexes sorted_abs_dfe_taps(k-1), and with
    no taps MATLAB errors 'sorted_abs_dfe_taps(1): out of bound 0'."""
    with pytest.raises(IndexError):
        Burst_Probability_Calc(_snr_struct(), [], _param(ndfe=3),
                               _op(nburst=3, simple=False))


def test_octave_float_levels_is_accepted():
    """COM Octave: every Octave/MATLAB number is a double, so ones(1,L) with
    L = 4 is exactly the L = 4.0 case, and the reference answers.
    np.ones(4.0) raised 'expected a sequence of integers or a single integer',
    and param.levels arrives from the config workbook as a float, so every run
    with OP.nburst > 0 crashed here."""
    p = _param()
    p.levels = 4.0
    p_burst, p_ep = Burst_Probability_Calc(_snr_struct(), [0.3, 0.2, 0.1], p,
                                           _op())
    np.testing.assert_allclose(p_ep, _OCT_SIMPLE_EP, rtol=1e-13)
    np.testing.assert_allclose(p_burst, _OCT_SIMPLE_BURST, rtol=1e-13)
