"""
assemble_sicopr.py — Assemble sicopr.py from individually verified py_impl.py files.

Do NOT edit sicopr.py directly. Edit the relevant py_impl.py, re-run its test,
then re-run this script.
"""
import os
import json
import re

HEADER = '''"""
sicopr.py — the SiCoPR engine
IEEE 802.3 Channel Operating Margin (COM), ported from the MATLAB reference
@@VERSION_BANNER@@

This file is machine-assembled from individually verified function translations
in com_functions/fn/*/py_impl.py. Do NOT edit this file directly.
To fix a function, edit its py_impl.py, re-run its test, then re-run assemble_sicopr.py.

@@TRANSLATION_REF@@

@@LICENSE@@
"""

import sys
import os
import re
import math
from math import factorial, ceil, floor, log, log2, log10, exp, sqrt, pi
import copy
import collections as _collections
import datetime
import hashlib as _hashlib
import warnings
from types import SimpleNamespace

import numpy as np
from scipy import signal as sp_signal
from scipy import interpolate as sp_interp
from scipy import special as sp_special
from scipy import linalg as sp_linalg

try:
    import openpyxl
except ImportError:
    openpyxl = None

try:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    _MPL_AVAILABLE = True
except ImportError:
    _MPL_AVAILABLE = False


def _ns(**kwargs):
    return SimpleNamespace(**kwargs)


def _ensure_array(v):
    if v is None:
        return np.array([], dtype=np.float64)
    return np.atleast_1d(np.asarray(v, dtype=np.float64)).ravel()


# Aliases so individual py_impl.py files can use bare names stripped of their imports
lfilter           = sp_signal.lfilter
fftconvolve       = sp_signal.fftconvolve
PchipInterpolator = sp_interp.PchipInterpolator
toeplitz          = sp_linalg.toeplitz
erfcinv           = sp_special.erfcinv
erfc              = sp_special.erfc



# ---------------------------------------------------------------------------
# Public entry point: run a full COM calculation from file paths
# ---------------------------------------------------------------------------

def _run_com(config_file, num_fext, num_next, s4p_files, export_mat=False):
    """Run end-to-end COM from a config .xlsx and a list of .s4p files.

    Parameters
    ----------
    config_file : str   Path to the COM settings spreadsheet (.xlsx)
    num_fext    : int   Number of FEXT aggressor channels
    num_next    : int   Number of NEXT aggressor channels
    s4p_files   : list  [thru, fext1, ..., next1, ...] in order
    export_mat  : bool  When True, write a per-case engineering .mat snapshot
                        (for R analysis) alongside the standard outputs. This is
                        an additive debug export; it does not change COM results.

    Returns
    -------
    results : list of SimpleNamespace  One entry per package test case
    """
    from functools import partial
    import time as _time
    _run_t0 = _time.time()  # wall-clock start, for the engineering-export run time

    # ── 1. Minimal OP bootstrap (read_ParamConfigFile will fill the rest) ──
    OP = SimpleNamespace()
    OP.DEBUG = False
    OP.DISPLAY_WINDOW = False
    OP.TDMODE = False
    OP.GET_FD = True  # MATLAB COM_CommandLine_Parse L1153 default; the Butterworth
                      # Rx filter reaches the signal only via FD_Processing's
                      # GET_FD-gated INCLUDE_FILTER block. TDMODE later forces False.
    OP.RxFFE = False
    OP.RxFFE_with_MMSE = False
    OP.FFE_OPT_METHOD = "FOM"
    OP.RX_CALIBRATION = False
    OP.PSDRXCAL = False
    OP.ERL_ONLY = False
    OP.WC_PORTZ = False
    OP.SNDR_REF = False
    OP.RESULT_DIR = ""

    # ── 2. Load config and S-parameters ───────────────────────────────────
    param, OP = read_ParamConfigFile(config_file, OP)
    # Per-run results directory (config name + timestamp) when the config's
    # RESULT_DIR field is blank. Per-case outputs land in <RESULT_DIR>/case_NN/.
    if not getattr(OP, 'RESULT_DIR', ''):
        _cfg_base = os.path.splitext(os.path.basename(config_file))[0]
        OP.RESULT_DIR = 'results_%s_%s' % (
            _cfg_base, datetime.datetime.now().strftime('%Y_%m_%d_%H_%M'))
    chdata, param = get_s4p_files(param, OP, num_fext, num_next, s4p_files)
    param.num_fext = num_fext
    param.num_next = num_next
    param.num_s4p_files = len(s4p_files)

    # ── Engineering .mat export (optional) ─────────────────────────────────
    # Pass-through inputs/metadata for com_mat_export; consumed per case.
    OP.EXPORT_MAT = bool(export_mat)
    OP.export_run_name = os.path.splitext(os.path.basename(config_file))[0]
    OP.export_config_file = config_file
    OP.export_s4p_files = list(s4p_files)
    OP.export_t_start = _run_t0

    # ── 3. Wire sub-functions (inject verified top-level implementations) ─
    _wired_get_TDR = partial(get_TDR,
        _Bessel_Thomson_Filter_fn=Bessel_Thomson_Filter,
        _Butterworth_Filter_fn=Butterworth_Filter,
        _Tukey_Window_fn=Tukey_Window,
        _s21_to_impulse_DC_fn=s21_to_impulse_DC,
        _get_StepR_fn=get_StepR,
        _get_PulseR_fn=get_PulseR,
        _get_pdf_fn=get_pdf_from_sampled_signal)

    _wired_process_sxp = partial(process_sxp,
        _plot_modal_fn=plot_modal,
        _add_pkg_with_die_fn=add_pkg_with_die,
        _get_RAW_FIR_fn=get_RAW_FIR,
        _get_TDR_fn=_wired_get_TDR)

    _wired_COM_FD_to_TD = partial(COM_FD_to_TD,
        _s21_to_impulse_DC_fn=s21_to_impulse_DC,
        _Bessel_Thomson_Filter_fn=Bessel_Thomson_Filter,
        _Butterworth_Filter_fn=Butterworth_Filter,
        _get_cm_noise_fn=get_cm_noise)

    _wired_FD_Processing = partial(FD_Processing,
        _get_ILN_fn=get_ILN,
        _get_ILN_cmp_td_fn=get_ILN_cmp_td,
        _capture_RIL_RILN_fn=capture_RIL_RILN,
        _Bessel_Thomson_Filter_fn=Bessel_Thomson_Filter,
        _Butterworth_Filter_fn=Butterworth_Filter,
        _Raised_Cosine_Filter_fn=Raised_Cosine_Filter,
        _Tx_FFE_Filter_fn=Tx_FFE_Filter)

    _wired_COM_eye_width = partial(COM_eye_width,
        _get_center_of_UI_fn=get_center_of_UI,
        _get_pdf_full_fn=get_pdf_full,
        _normal_dist_fn=normal_dist,
        _conv_fct_fn=conv_fct,
        _conv_fct_MNZ_fn=conv_fct_MeanNotZero,
        _get_pdf_ss_fn=get_pdf_from_sampled_signal,
        _pdf_to_cdf_fn=pdf_to_cdf,
        _cdf_to_ber_fn=cdf_to_ber_contour,
        _find_eye_width_fn=find_eye_width,
        _combine_pdf_fn=combine_pdf_same_voltage_axis)

    _wired_get_PSDs = partial(get_PSDs,
        _S_RN_fn=S_RN,
        _S_IN_fn=S_IN,
        _H_interp_fn=H_interp)

    _wired_OptFom_Calc_FOM = partial(OptFom_Calc_FOM,
        _COM_eye_width_fn=_wired_COM_eye_width)

    _wired_optimize_fom = partial(optimize_fom,
        _OptFom_Initialize_Loop_Struct_fn=OptFom_Initialize_Loop_Struct,
        _OptFom_Build_TXFFE_fn=OptFom_Build_TXFFE,
        _OptFom_Calculate_Settings_fn=OptFom_Calculate_Settings,
        _FD_CTLE_fn=FD_CTLE,
        _OptFom_Compute_CTLE_fn=OptFom_Compute_CTLE,
        _OptFom_Calc_Noise_XC_fn=OptFom_Calc_Noise_XC,
        _get_sigma_eta_ACCM_noise_fn=get_sigma_eta_ACCM_noise,
        _get_sigma_noise_fn=get_sigma_noise,
        _OptFom_Compute_TXFFE_fn=OptFom_Compute_TXFFE,
        _OptFom_Find_Sample_Point_fn=OptFom_Find_Sample_Point,
        _OptFom_Setup_Sampler_Sweep_fn=OptFom_Setup_Sampler_Sweep,
        _OptFom_Itick_BoxSearch_fn=OptFom_Itick_BoxSearch,
        _OptFom_Itick_LocalSearch_fn=OptFom_Itick_LocalSearch,
        _OptFom_Compute_RxFFE_fn=OptFom_Compute_RxFFE,
        _OptFom_Compute_DFE_fn=OptFom_Compute_DFE,
        _OptFom_Calc_Noise_fn=OptFom_Calc_Noise,
        _OptFom_Calc_FOM_fn=_wired_OptFom_Calc_FOM,
        _OptFom_Local_Search_fn=OptFom_Local_Search,
        _OptFom_Adaptive_Local_Search_fn=OptFom_Adaptive_Local_Search,
        _get_PSDs_fn=_wired_get_PSDs,
        _OptFom_Set_Best_Itick_fn=OptFom_Set_Best_Itick,
        _OptFom_Update_Best_Setttings_fn=OptFom_Update_Best_Setttings,
        _OptFom_Update_Best_Settings_EQ_Failed_fn=OptFom_Update_Best_Settings_EQ_Failed,
        _OptFom_Update_BEST_Post_Optimize_fn=OptFom_Update_BEST_Post_Optimize,
        _OptFom_Create_Output_fn=OptFom_Create_Output)

    # ── 4. Run ─────────────────────────────────────────────────────────────
    results = com_ieee8023_(param, OP, chdata,
        _parameter_size_adjustment_fn=parameter_size_adjustment,
        _read_s4p_files_fn=read_s4p_files,
        _process_sxp_fn=_wired_process_sxp,
        _FD_Processing_fn=_wired_FD_Processing,
        _COM_FD_to_TD_fn=_wired_COM_FD_to_TD,
        _optimize_fom_fn=_wired_optimize_fom,
        _Apply_EQ_fn=Apply_EQ,
        _get_pdf_fn=get_pdf,
        _Create_Noise_PDF_fn=Create_Noise_PDF,
        _TDR_ERL_Processing_fn=TDR_ERL_Processing,
        _COM_eye_width_fn=_wired_COM_eye_width,
        _get_PSDs_fn=_wired_get_PSDs,
        _MLSE_U1_c_178A_fn=MLSE_U1_c_178A,
        _Output_Arg_Fill_fn=Output_Arg_Fill)

    return results


'''

# --- version banner -------------------------------------------------------
# Kept in VERSION.json rather than in the literal above, because the literal
# hardcoded "4p14p0" and stayed that way through two revision moves: the port
# retargeted to 4p15p0 for the correlation corpus, then gained 4p16p0 support,
# while every generated sicopr.py still announced 4p14p0.
_VERSION = json.load(open(os.path.join(os.path.dirname(os.path.abspath(__file__)),
                                       'VERSION.json'), encoding='utf-8'))
_REF = _VERSION['primary_reference']
HEADER = HEADER.replace(
    '@@VERSION_BANNER@@',
    'Emulates com_ieee8023_%s by default; %s supported via --matlab-version\n'
    '(or sicopr.COM_MATLAB_VERSION, or a "COM Version" keyword in the config).'
    % (_VERSION['default_matlab_version'],
       ' and '.join(_VERSION['supported_matlab_versions']))
).replace(
    '@@TRANSLATION_REF@@',
    'Translation reference: %s (%d lines, %d functions)\nVersion metadata: VERSION.json'
    % (os.path.basename(_REF['file']), _REF['lines'], _REF['functions'])
).replace(
    '@@LICENSE@@',
    # BSD-3-Clause requires the notice to travel with redistributed source, and
    # sicopr.py is the single file most users will actually receive.
    '%s\n%s\nSPDX-License-Identifier: %s\n\n%s'
    % (_VERSION['license']['original_copyright'],
       _VERSION['license']['port_copyright'],
       _VERSION['license']['spdx'],
       _VERSION['license']['note']))

# Load and sort functions by MATLAB line number
with open('com_functions/registry.json', encoding='utf-8-sig') as f:
    reg = json.load(f)

fns = reg['functions']
fns_sorted = sorted(fns, key=lambda x: x['matlab_lines'][0])

collected_lines = [HEADER]
fn_count = 0
not_impl_count = 0
deferred_aliases = []  # (alias_name, target_name) pairs emitted after all functions

_PRIVATE_DEF_RE = re.compile(r'^(def )(_\w+)(\s*\()', re.MULTILINE)


def _namespace_private_helpers(src, module_name):
    """Rename all top-level private helper functions to _MODULE__original_name.

    This prevents collisions when multiple py_impl.py files define helpers
    with the same private name (e.g. _conv_fct, _s21_to_impulse_DC).
    Only top-level (unindented) 'def _name(' definitions are renamed;
    their call-sites in the same file are renamed via whole-word substitution.
    """
    # Collect all top-level private helper names in this file
    private_names = set(_PRIVATE_DEF_RE.findall(src))  # returns (prefix, name, suffix) tuples
    private_names = {t[1] for t in private_names}      # just the names
    if not private_names:
        return src
    # Sort longest-first to avoid partial replacements (e.g. _foo before _foobar)
    for pname in sorted(private_names, key=len, reverse=True):
        new_name = f'_{module_name}__{pname[1:]}'
        src = re.sub(r'\b' + re.escape(pname) + r'\b', new_name, src)
    return src


for fn in fns_sorted:
    name = fn['name']
    impl_path = os.path.join('com_functions', 'fn', name, 'py_impl.py')
    if not os.path.exists(impl_path):
        raise FileNotFoundError(f'Missing: {impl_path}')

    with open(impl_path, encoding='utf-8') as f:
        src = f.read()

    # Namespace private helpers before any other processing
    src = _namespace_private_helpers(src, name)

    src_lines = src.splitlines()
    body_lines = []
    in_main = False
    _alias_re = re.compile(r'^from\s+\S+\s+import\s+(\w+)\s+as\s+(_\w+)\s*$')
    for line in src_lines:
        stripped = line.strip()
        # Skip only top-level (unindented) import lines — keep indented imports
        # (indented imports appear inside try/except blocks and must stay)
        if not line.startswith(' ') and not line.startswith('\t'):
            if stripped.startswith('import ') or stripped.startswith('from '):
                # Special case: 'from X import Y as _Z' → defer alias until after all fns
                m = _alias_re.match(stripped)
                if m:
                    deferred_aliases.append((m.group(2), m.group(1)))
                continue
        # Skip __main__ blocks (handle both single and double quote variants)
        if stripped in ("if __name__ == '__main__':", 'if __name__ == "__main__":'):
            in_main = True
        if in_main:
            continue
        body_lines.append(line)

    # Fix any empty try: blocks left after stripping top-level imports
    fixed = []
    i = 0
    while i < len(body_lines):
        fixed.append(body_lines[i])
        if body_lines[i].rstrip() == 'try:':
            j = i + 1
            while j < len(body_lines) and body_lines[j].strip() == '':
                j += 1
            if j < len(body_lines) and body_lines[j].lstrip().startswith('except'):
                fixed.append('    pass')
        i += 1
    body_lines = fixed

    body = '\n'.join(body_lines).strip()
    if body:
        collected_lines.append(f'\n# --- {name} (MATLAB lines {fn["matlab_lines"][0]}–{fn["matlab_lines"][1]}) ---\n')
        collected_lines.append(body)
        collected_lines.append('\n')
        fn_count += 1

    if 'NotImplementedError' in src:
        not_impl_count += 1

# Emit deferred aliases after all functions are defined
if deferred_aliases:
    alias_lines = ['\n# --- cross-module import aliases (resolved after all functions) ---']
    for alias_name, target_name in deferred_aliases:
        alias_lines.append(f'{alias_name} = {target_name}')
    collected_lines.append('\n'.join(alias_lines) + '\n')

# CLI entry point
collected_lines.append("""

if __name__ == '__main__':
    import argparse
    import sys as _sys
    parser = argparse.ArgumentParser(description='IEEE 802.3 COM calculator')
    parser.add_argument('config_file')
    parser.add_argument('thru_s4p')
    parser.add_argument('--fext', nargs='*', default=[])
    parser.add_argument('--next', nargs='*', default=[])
    parser.add_argument('--export-mat', action='store_true',
                        help='also write a per-case engineering .mat snapshot for R analysis')
    parser.add_argument('--matlab-version', choices=['4p15p0', '4p16p0'],
                        help='which MATLAB release to emulate. Default 4p15p0, the '
                             'version the 208-case reference corpus and the whole '
                             'correlation result were produced with. 4p16p0 enables '
                             'the newer behaviour -- see docs/MATLAB_4p16p0_CHANGES.md')
    parser.add_argument('--eye-under-mlse', action='store_true',
                        help='compute the eye contour and timing bathtub for PLOTTING even '
                             'when MLSE is enabled. MATLAB gates the eye on MLSE == 0 '
                             '(4p15p0 L620), but MLSE is applied afterwards, so the pre-MLSE '
                             '(DFE-only) eye is well defined. Diagnostic only: no reported '
                             'COM, VEC, VEO or EW value changes.')
    args = parser.parse_args()
    if args.matlab_version:
        COM_MATLAB_VERSION = args.matlab_version
        print(f'MATLAB version emulated: {COM_MATLAB_VERSION}')
    if args.eye_under_mlse:
        EYE_PLOT_UNDER_MLSE = True
    _fext = args.fext or []
    _next = args.next or []
    _s4p_files = [args.thru_s4p] + _fext + _next
    _num_fext = len(_fext)
    _num_next = len(_next)
    print(f'Running COM: {args.config_file}')
    print(f'FEXT: {_num_fext}, NEXT: {_num_next}')
    print(f'Files: {_s4p_files}')
    print()
    _results = _run_com(args.config_file, _num_fext, _num_next, _s4p_files,
                        export_mat=args.export_mat)
    if _results is None:
        print('ERROR: COM returned None.')
        _sys.exit(1)
    # com_ieee8023_ unwraps a single-package-case run to a bare struct (matches MATLAB
    # 'if length(results)==1, results = results{1}'). Normalize to a list so the per-case
    # print works for both single- and multi-case configs.
    if not isinstance(_results, list):
        _results = [_results]
    for _i, _r in enumerate(_results):
        if _r is None:
            continue
        print(f'--- Case {_i + 1} ---')
        for _attr in ['COM_dB', 'VEO_mV', 'VEC_dB', 'FOM_ILD', 'ICN_mV']:
            _val = getattr(_r, _attr, 'N/A')
            if isinstance(_val, float):
                print(f'  {_attr:30s} = {_val:.4f}')
            else:
                print(f'  {_attr:30s} = {_val}')
        _thr = float(getattr(_r, 'pass_threshold', 3.0))
        _com = getattr(_r, 'COM_dB', None)
        if _com is not None:
            print(f'  {"Result":30s} = {"PASS" if float(_com) >= _thr else "FAIL"}  (threshold {_thr:.1f} dB)')
        print()
""")

output = '\n'.join(collected_lines)

with open('sicopr.py', 'w', encoding='utf-8') as f:
    f.write(output)

print(f'Assembled sicopr.py from {fn_count} functions.')
if not_impl_count:
    print(f'WARNING: {not_impl_count} function(s) still contain NotImplementedError.')
else:
    print('OK: No NotImplementedError stubs remain.')
