"""Verification tests for COM_CommandLine_Parse().

# ============================================================
# MATLAB GROUND TRUTH (lines 1149-1200)
# Parses command-line arguments for COM.
# Legacy mode: config_file, num_fext, num_next.
# TD mode: sets OP.TDMODE=True, OP.GET_FD=False.
# Config2Mat mode: sets OP.CONFIG2MAT_ONLY=True.
# Empty varargin: returns defaults.
# ============================================================
"""
import pytest
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..'))
from com_functions.fn.COM_CommandLine_Parse.py_impl import COM_CommandLine_Parse
from types import SimpleNamespace


def _OP():
    return SimpleNamespace()


def test_empty_args_defaults():
    """Empty varargin returns default OP with TDMODE=False."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP())
    assert OP.TDMODE is False
    assert OP.GET_FD is True
    assert cfg == ''


def test_legacy_mode_config_file():
    """Legacy mode parses config_file as first positional arg."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP(), 'my_config.csv', 2, 1)
    assert cfg == 'my_config.csv'
    assert nfext == 2
    assert nnext == 1


def test_td_mode_sets_flags():
    """TD keyword sets TDMODE=True and GET_FD=False."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP(), 'TD', 'ch.csv', 0, 0)
    assert OP.TDMODE is True
    assert OP.GET_FD is False
    assert cfg == 'ch.csv'


def test_config2mat_mode():
    """Config2Mat keyword sets CONFIG2MAT_ONLY=True."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP(), 'Config2Mat', 'cfg.xlsx')
    assert OP.CONFIG2MAT_ONLY is True
    assert cfg == 'cfg.xlsx'


def test_remember_keyword_td():
    """Remember_keyword is 'TD' when TD keyword used."""
    _, _, _, kw, OP, _ = COM_CommandLine_Parse(_OP(), 'TD', 'cfg.csv', 0, 0)
    assert kw.upper() == 'TD'


def test_legacy_no_fext_next_when_string_follows():
    """When next arg is non-numeric string, num_fext/num_next default to 0."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP(), 'ch.csv', 'extra')
    assert nfext == 0
    assert nnext == 0
    assert cfg == 'ch.csv'


# ============================================================
# COM Octave oracle values (2026-09-22)
# Generated by running COM_CommandLine_Parse verbatim from
# octave/com_ieee8023_4p16p0_octave_compat.m under Octave via
# tools/octave_oracle.py, with varargin_extractor as a subfunction.
#
# Two divergences these pin:
#  1. the keyword MATCH is strcmpi (case-insensitive) but the two switch
#     statements that act on it are case-SENSITIVE, so a lowercase keyword is
#     consumed and then selects nothing;
#  2. the "omit num_fext/num_next" trigger is isempty(str2num(s)), and
#     str2num is an eval, so 'pi', '0 0', '[1 2]', '1:5' and 'true' are all
#     numeric and take the normal branch.
# ============================================================


def test_octave_lowercase_td_selects_no_case():
    """COM Octave: ('td','cfg.csv',0,0) -> TDMODE=0, GET_FD=1, config_file='',
    num_fext=[], num_next=[], varargin={'cfg.csv',0,0}."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(
        _OP(), 'td', 'cfg.csv', 0, 0)
    assert OP.TDMODE is False
    assert OP.GET_FD is True
    assert cfg == ''
    assert nfext is None
    assert nnext is None
    assert kw == 'td'
    assert rest == ['cfg.csv', 0, 0]


def test_octave_lowercase_legacy_selects_no_case():
    """COM Octave: ('legacy','cfg.csv',2,1) -> config_file='', num_fext=[],
    num_next=[], varargin={'cfg.csv',2,1}."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(
        _OP(), 'legacy', 'cfg.csv', 2, 1)
    assert cfg == ''
    assert nfext is None
    assert nnext is None
    assert kw == 'legacy'
    assert rest == ['cfg.csv', 2, 1]


def test_octave_lowercase_config2mat_selects_no_case():
    """COM Octave: ('config2mat','cfg.xlsx') -> CONFIG2MAT_ONLY=0,
    config_file='', varargin={'cfg.xlsx'}."""
    cfg, _, _, kw, OP, rest = COM_CommandLine_Parse(
        _OP(), 'config2mat', 'cfg.xlsx')
    assert OP.CONFIG2MAT_ONLY is False
    assert cfg == ''
    assert kw == 'config2mat'
    assert rest == ['cfg.xlsx']


def test_octave_uppercase_config2mat_selects_no_case():
    """COM Octave: ('CONFIG2MAT','cfg.xlsx') is matched by strcmpi and
    consumed, but the switch does not take it either."""
    cfg, _, _, kw, OP, rest = COM_CommandLine_Parse(
        _OP(), 'CONFIG2MAT', 'cfg.xlsx')
    assert OP.CONFIG2MAT_ONLY is False
    assert cfg == ''
    assert rest == ['cfg.xlsx']


def test_octave_td_alone_gives_empty_config_file():
    """COM Octave: ('TD') -> varargin_extractor on an empty varargin returns
    MATLAB [], not '': config_file is [] (0x0 double), mapped to None."""
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(_OP(), 'TD')
    assert OP.TDMODE is True
    assert cfg is None
    assert nfext is None
    assert nnext is None
    assert rest == []


def test_octave_config2mat_alone_gives_empty_config_file():
    """COM Octave: ('Config2Mat') -> CONFIG2MAT_ONLY=1, config_file=[]."""
    cfg, _, _, _, OP, rest = COM_CommandLine_Parse(_OP(), 'Config2Mat')
    assert OP.CONFIG2MAT_ONLY is True
    assert cfg is None
    assert rest == []


@pytest.mark.parametrize('arg', ['pi', 'e', 'eps', '0 0', '1,2', '[1 2]',
                                 '1:5', 'true', 'false', '2', '-4', '1e3'])
def test_octave_str2num_numeric_takes_normal_branch(arg):
    """COM Octave: str2num of each of these is non-empty, so the string is
    taken as num_fext and num_next falls off the end as []."""
    cfg, nfext, nnext, _, _, rest = COM_CommandLine_Parse(_OP(), 'cfg.csv', arg)
    assert cfg == 'cfg.csv'
    assert nfext == arg
    assert nnext is None
    assert rest == []


@pytest.mark.parametrize('arg', ['extra', 'cfg.csv', 'ans', '', '[]'])
def test_octave_str2num_empty_takes_zero_branch(arg):
    """COM Octave: str2num of each of these is [], so num_fext and num_next
    are both set to 0 and the argument is left in varargin."""
    cfg, nfext, nnext, _, _, rest = COM_CommandLine_Parse(_OP(), 'cfg.csv', arg)
    assert cfg == 'cfg.csv'
    assert nfext == 0
    assert nnext == 0
    assert rest == [arg]


def test_octave_non_char_first_argument_errors():
    """COM Octave: error('First input must be a string')."""
    with pytest.raises(TypeError):
        COM_CommandLine_Parse(_OP(), 5)


def test_octave_explicit_legacy_keyword():
    """COM Octave: ('Legacy','cfg.csv',2,1) -> the keyword is consumed and the
    three positional arguments follow it:
        config_file='cfg.csv', num_fext=2, num_next=1, Remember_keyword='Legacy'
    """
    cfg, nfext, nnext, kw, OP, rest = COM_CommandLine_Parse(
        _OP(), 'Legacy', 'cfg.csv', 2, 1)
    assert cfg == 'cfg.csv'
    assert nfext == 2
    assert nnext == 1
    assert kw == 'Legacy'
    assert OP.TDMODE is False
    assert OP.CONFIG2MAT_ONLY is False
    assert rest == []
